# Generated by Django 4.2 on 2025-04-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ipd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('datetime_admission', models.CharField(max_length=250)),
                ('patient_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('bed_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bed')),
            ],
        ),
    ]
