# Generated by Django 4.2 on 2025-05-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ipd'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='datetime_discharge',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ipd',
            name='dd_note',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
