# Generated by Django 4.2 on 2025-05-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_ipd_datetime_discharge_ipd_dd_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='scalp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.CharField(max_length=250)),
                ('date', models.CharField(max_length=250)),
                ('datetime_admission', models.CharField(max_length=250)),
                ('patient_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=250)),
                ('address', models.TextField()),
                ('mobile', models.BigIntegerField()),
                ('datetime_discharge', models.CharField(blank=True, max_length=250, null=True)),
                ('fees', models.IntegerField(default=0)),
            ],
        ),
    ]
