# Generated by Django 4.2 on 2025-05-12 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_complaint_past_history_personal_h_o'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poller', models.BooleanField(default=False)),
                ('icterus', models.BooleanField(default=False)),
                ('LAP', models.CharField(blank=True, max_length=250)),
                ('clubbing', models.BooleanField(default=False)),
                ('cyanosis', models.BooleanField(default=False)),
                ('complaints', models.ManyToManyField(to='myapp.complaint')),
                ('past_history', models.ManyToManyField(to='myapp.past_history')),
                ('personal_H_O', models.ManyToManyField(to='myapp.personal_h_o')),
            ],
        ),
        migrations.CreateModel(
            name='FC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referrer', models.CharField(max_length=250)),
                ('patient_name', models.CharField(max_length=250)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('mobile_no', models.BigIntegerField()),
                ('Opinion', models.TextField()),
                ('patient_condition', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='myapp.patientcondition')),
            ],
        ),
    ]
