# Generated by Django 4.2 on 2025-05-13 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_admin_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_login',
            name='mobile_no',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
