# Generated by Django 4.2 on 2025-05-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_admin_login_mobile_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin_login',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
