# Generated by Django 4.2 on 2025-05-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_service_specialization_opd_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opd',
            name='service_id',
        ),
        migrations.AddField(
            model_name='opd',
            name='service_id',
            field=models.ManyToManyField(to='myapp.service'),
        ),
    ]
