# Generated by Django 4.2 on 2025-05-16 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_remove_opd_service_id_opd_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='opd',
            name='doctor_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor'),
        ),
    ]
