# Generated by Django 4.2 on 2025-05-16 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_opd_doctor_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='opd',
            name='total_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
