# Generated by Django 4.2 on 2025-05-20 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_opd_total_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('mobile_no', models.BigIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('date_of_joining', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
