# Generated by Django 4.2 on 2025-06-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_ad'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='salary_detail',
            field=models.TextField(default='{}'),
        ),
    ]
