# Generated by Django 4.2 on 2025-06-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_staff_salary_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='salary_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
