# Generated by Django 4.2 on 2025-06-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_staff_salary_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='salary_detail',
        ),
        migrations.AlterField(
            model_name='patientcondition',
            name='LAP',
            field=models.BooleanField(default=False),
        ),
    ]
