# Generated by Django 4.2 on 2025-06-04 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_remove_staff_salary_detail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcondition',
            name='edema_feet',
            field=models.BooleanField(default=False),
        ),
    ]
