# Generated by Django 4.2 on 2025-06-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_patientcondition_edema_feet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fc',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
