# Generated by Django 4.2 on 2025-06-04 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_fc_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcondition',
            name='ECG',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientcondition',
            name='blood_pressure',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientcondition',
            name='blood_sugar',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientcondition',
            name='pulse',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientcondition',
            name='temperature',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
