# Generated by Django 4.2 on 2025-06-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_patientcondition_ecg_patientcondition_blood_pressure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fc',
            name='date',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
