# Generated by Django 4.2 on 2025-06-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_ipd_doctor_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalp',
            name='bed_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.bed'),
        ),
        migrations.AddField(
            model_name='scalp',
            name='doctor_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor'),
        ),
    ]
