# Generated by Django 4.2 on 2025-06-05 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_scalp_bed_data_scalp_doctor_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='DC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('date', models.CharField(blank=True, max_length=255, null=True)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField()),
                ('date_of_admission', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_discharge', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_discharge', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis', models.CharField(blank=True, max_length=255, null=True)),
                ('clinical_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('investigation', models.CharField(blank=True, max_length=255, null=True)),
                ('treatment_given', models.CharField(blank=True, max_length=255, null=True)),
                ('bed_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bed')),
            ],
        ),
    ]
