# Generated by Django 4.2 on 2025-06-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_dc_patient_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='date_of_joining',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staff',
            name='date_of_joining',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
