# Generated by Django 4.2 on 2025-06-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_alter_doctor_date_of_joining_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd',
            name='date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
