# Generated by Django 4.2.23 on 2025-06-11 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='opd',
            name='chief_complaints',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='opd',
            name='examination',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='opd',
            name='given_medicine',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='opd',
            name='vitals',
            field=models.JSONField(default=dict),
        ),
    ]
