# Generated by Django 5.0.7 on 2025-06-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_opd_chief_complaints_opd_examination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='diagnosis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
