# Generated by Django 5.0.7 on 2025-06-26 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='opd',
            name='diagnosis_detail',
            field=models.JSONField(default=list),
        ),
    ]
