# Generated by Django 5.0.7 on 2025-07-04 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_opd_diagnosis_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='payment_details',
            field=models.JSONField(default=list),
        ),
    ]
