# Generated by Django 5.0.7 on 2025-07-04 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_ipd_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='past_historys',
            field=models.JSONField(default=list),
        ),
    ]
