# Generated by Django 5.0.7 on 2025-07-04 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_ipd_past_historys'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='daily_chief_complaints',
            field=models.JSONField(default=list),
        ),
    ]
