# Generated by Django 5.0.7 on 2025-07-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_ipd_daily_chief_complaints'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='systemetic_examination',
            field=models.JSONField(default=list),
        ),
    ]
