# Generated by Django 5.0.7 on 2025-07-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_ipd_systemetic_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='general_examination',
            field=models.JSONField(default=list),
        ),
    ]
