# Generated by Django 5.0.7 on 2025-07-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_ipd_general_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='given_medicine',
            field=models.JSONField(default=list),
        ),
    ]
