# Generated by Django 5.0.7 on 2025-07-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_ipd_given_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='daily_given_treatment',
            field=models.JSONField(default=list),
        ),
    ]
