# Generated by Django 5.0.7 on 2025-07-04 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_ipd_daily_given_treatment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='daily_examination',
            field=models.JSONField(default=list),
        ),
    ]
