# Generated by Django 5.0.7 on 2025-07-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_ipd_daily_examination'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='date_of_refer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='ipd',
            name='referred_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
