# Generated by Django 5.0.7 on 2025-07-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_ipd_date_of_refer_ipd_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
