# Generated by Django 5.0.7 on 2025-07-04 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_ipd_advice'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='discharge_condition',
            field=models.TextField(blank=True, null=True),
        ),
    ]
