# Generated by Django 5.0.7 on 2025-07-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_ipd_discharge_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='final_diagnosis',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='ipd',
            name='pravisional_diagnosis',
            field=models.JSONField(default=list),
        ),
    ]
