# Generated by Django 5.0.7 on 2025-07-09 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_ipd_final_diagnosis_ipd_pravisional_diagnosis'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipd',
            old_name='pravisional_diagnosis',
            new_name='provisional_diagnosis',
        ),
    ]
