# Generated by Django 5.0.7 on 2025-07-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_rename_pravisional_diagnosis_ipd_provisional_diagnosis'),
    ]

    operations = [
        migrations.AddField(
            model_name='opd',
            name='discount_applied',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='opd',
            name='past_history',
            field=models.ManyToManyField(blank=True, null=True, to='myapp.past_history'),
        ),
    ]
