# Generated by Django 5.0.7 on 2025-07-26 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_opd_discount_applied_opd_past_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='opinion_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opinion_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
