# Generated by Django 5.0.7 on 2025-07-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_opinion_details_medicine_medicine_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcondition',
            name='CNS',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientcondition',
            name='CVS',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientcondition',
            name='PA',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientcondition',
            name='RS',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='patientcondition',
            name='datetime',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
