# Generated by Django 5.0.7 on 2025-07-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_patientcondition_cns_patientcondition_cvs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fc',
            name='posted_for',
            field=models.TextField(blank=True, null=True),
        ),
    ]
