# Generated by Django 5.0.7 on 2025-08-01 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_fc_posted_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientcondition',
            name='staff_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.staff'),
        ),
        migrations.RemoveField(
            model_name='opd',
            name='past_history',
        ),
        migrations.AddField(
            model_name='opd',
            name='past_history',
            field=models.JSONField(default=list),
        ),
    ]
