# Generated by Django 5.0.7 on 2025-08-04 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_patientcondition_staff_data_remove_opd_past_history_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='brand_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
