# Generated by Django 5.0.7 on 2025-08-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_medicine_brand_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='composition',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
