# Generated by Django 5.0.7 on 2025-08-08 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_medicine_composition'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='service_id',
            field=models.ManyToManyField(blank=True, to='myapp.service'),
        ),
    ]
