# Generated by Django 5.0.7 on 2025-08-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_ipd_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='dc',
            name='given_medicine',
            field=models.JSONField(default=list),
        ),
    ]
