# Generated by Django 5.0.7 on 2025-08-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_dc_given_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='discharge_status',
            field=models.TextField(blank=True, null=True),
        ),
    ]
