# Generated by Django 5.0.6 on 2025-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_ipd_discharge_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipd',
            name='final_diagnosis',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='ipd',
            name='provisional_diagnosis',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
