# Generated by Django 5.0.6 on 2025-08-13 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0057_alter_ipd_final_diagnosis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipd',
            name='daily_chief_complaints',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
