# Generated by Django 5.0.6 on 2025-08-14 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_alter_ipd_daily_chief_complaints'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_service_name', models.CharField(blank=True, max_length=250, null=True)),
                ('fees', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
