# Generated by Django 5.0.6 on 2025-08-14 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_hospitalservice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospitalservice',
            old_name='hospital_service_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='hospitalservice',
            name='fees',
        ),
    ]
