# Generated by Django 5.0.6 on 2025-08-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_rename_hospital_service_name_hospitalservice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='personal_H_O',
            field=models.JSONField(default=list),
        ),
    ]
