# Generated by Django 5.0.6 on 2025-08-18 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_ipd_personal_h_o'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='investigation_chart',
            field=models.JSONField(default=list),
        ),
    ]
