# Generated by Django 5.0.6 on 2025-08-18 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_ipd_investigation_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='treatment_chart',
            field=models.JSONField(default=list),
        ),
    ]
