# Generated by Django 5.0.6 on 2025-08-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_ipd_treatment_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipd',
            name='hospital_service_data',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
