# Generated by Django 5.0.6 on 2025-09-03 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_ipd_hospital_service_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discharge_ipd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('mobile', models.CharField(max_length=15)),
                ('datetime_admission', models.CharField(max_length=150)),
                ('datetime_discharge', models.CharField(max_length=100)),
                ('type_of_discharge', models.CharField(max_length=100)),
                ('diagnosis', models.JSONField(default=list)),
                ('clinical_notes', models.JSONField(default=list)),
                ('discharge_condition', models.JSONField(default=dict)),
                ('treatment_chart', models.JSONField(default=list)),
                ('Rx', models.JSONField(default=list)),
                ('next_visit', models.CharField(blank=True, max_length=255, null=True)),
                ('advice', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('bed_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.bed')),
                ('doctor_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.doctor')),
                ('ipd_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.ipd')),
                ('staff_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.staff')),
            ],
        ),
    ]
