# Generated by Django 5.0.6 on 2025-09-03 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_discharge_ipd'),
    ]

    operations = [
        migrations.AddField(
            model_name='discharge_ipd',
            name='date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discharge_ipd',
            name='date_of_refer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discharge_ipd',
            name='dd_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='discharge_ipd',
            name='referred_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='discharge_ipd',
            name='sr_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='discharge_ipd',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
    ]
