# Generated by Django 5.0.6 on 2025-09-22 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_delete_ad_delete_admin_login_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bed',
            new_name='Designation',
        ),
    ]
