# Generated by Django 5.0.6 on 2025-09-22 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_rename_bed_designation'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=250, null=True)),
                ('school_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('school_address', models.TextField(blank=True, null=True)),
                ('contact_person_name', models.CharField(blank=True, max_length=250, null=True)),
                ('contact_number', models.IntegerField(blank=True, null=True)),
                ('address_line_1', models.TextField(blank=True, null=True)),
                ('address_line_2', models.TextField(blank=True, null=True)),
                ('landmark', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('district', models.CharField(blank=True, max_length=250, null=True)),
                ('designation_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.designation')),
            ],
        ),
    ]
