# Generated by Django 5.0.6 on 2025-09-23 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_school'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.TextField()),
                ('job_type', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=100)),
                ('experience_required', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=255)),
                ('salary_range', models.CharField(max_length=50)),
                ('posted_date', models.CharField(max_length=255)),
                ('last_date_to_apply', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('school_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.school')),
            ],
        ),
    ]
