# Generated by Django 5.0.6 on 2025-09-23 08:56

import django_mysql.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.JSONField()),
                ('qualification', models.CharField(max_length=255)),
                ('experience', models.CharField(max_length=50)),
                ('subjects', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=255, null=True), blank=True, default=[], null=True, size=100)),
                ('preferred_classes', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=255, null=True), blank=True, default=[], null=True, size=100)),
                ('resume_url', models.FileField(blank=True, null=True, upload_to='resumes')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile_images')),
                ('youtube_link', models.URLField(blank=True, null=True)),
                ('expected_salary', models.CharField(max_length=50)),
                ('availability', models.CharField(max_length=50)),
                ('skills', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=255, null=True), blank=True, default=[], null=True, size=100)),
                ('languages_known', django_mysql.models.ListTextField(models.CharField(blank=True, max_length=255, null=True), blank=True, default=[], null=True, size=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
