# Generated by Django 5.0.6 on 2025-09-23 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_alter_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
