# Generated by Django 5.0.6 on 2025-09-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_alter_teacher_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='address',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
